; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Common settings applied to all environments
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:main]
platform = espressif8266
board = nodemcuv2
build_src_filter = -<*> +<main/>  
upload_port = COM10


[env:shield]
build_src_filter = -<*> +<shield/>
board = freenove_esp32_wrover ;change this later to the actual board
upload_port = COM8
lib_deps = 
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14


[env:sword]
build_src_filter = -<*> +<sword/>
board = freenove_esp32_wrover
upload_port = COM8
lib_deps = 
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14

[env:bow]
build_src_filter = -<*> +<bow/>
board = freenove_esp32_wrover
upload_port = COM8
lib_deps = 
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14



[env:i2cscnaner]
build_src_filter = -<*> +<i2cscnaner/>
board = freenove_esp32_wrover
upload_port = COM8
